# Generated by Django 5.1.4 on 2024-12-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('date_time', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('upcomming', 'upcomming'), ('ongoing', 'ongoing'), ('completed', 'completed')], max_length=30)),
            ],
        ),
    ]
